# Generated by Django 3.1.4 on 2020-12-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTypeCompatibility',
            fields=[
                ('blood_type_compatibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_compatible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_type_compatibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodTypes',
            fields=[
                ('blood_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_type', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'blood_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('donation_history_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('donation_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'donation_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonationModes',
            fields=[
                ('donation_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_mode', models.CharField(max_length=45)),
                ('donation_freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donation_modes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonationReg',
            fields=[
                ('donation_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donation_reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonationsDonationModes',
            fields=[
                ('donations_donation_modes_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'donations_donation_modes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('event_desc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'priority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_title', models.CharField(blank=True, max_length=50, null=True)),
                ('request_start_date', models.DateField(blank=True, null=True)),
                ('request_end_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionMode',
            fields=[
                ('subscription_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_mode', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'subscription_mode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEventSubscription',
            fields=[
                ('user_event_subscription_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_event_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
                ('reputation', models.IntegerField()),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_address', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_lat_lon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'venues',
                'managed': False,
            },
        ),
    ]
